modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/TheMrMilchmann/Fency/issues"

[[mods]]
modId="fency"
version="${file.jarVersion}"
displayName="Fency"
displayURL="https://github.com/TheMrMilchmann/Fency"
authors="TheMrMilchmann, Drados"
description='''
Have you ever been annoyed by that one cow that just didn't want to stay in its pen and managed to get out just before
you could close the fence gate?

_Fency_ is small QoL mod that helps in exactly this scenario by preventing mobs that are not leashed from passing
through fence gates. Mobs that are leashed to a fence cannot pass either. The behavior of mobs that cannot be leashed
remains unchanged.
'''