[versions]
neoforge = "21.3.52-beta"


[libraries]
# net.neoforged:neoforge - NeoForge
# https://github.com/neoforged/NeoForge
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }