[versions]
curseforge-publish = "0.4.0"
minecraft = "1.19.3"

[libraries]
# androidx.compose.compiler:compiler
gradle-curseforge-publish = { module = "io.github.themrmilchmann.gradle.publish.curseforge:gradle-curseforge-publish", version.ref = "curseforge-publish" }