name: CI
on:
  - pull_request
  - push
  - workflow_dispatch


env:
  JDK_VERSION: "21"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info -S --show-version
          gradle-home-cache-cleanup: true